####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode.
#
# Before building the container image run:
#
# ./mvnw package -Dnative
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.native -t quarkus/rimfrost-regel-rtf-manuell-komplettering-bff .
#
# Then run the container using:
#
# docker run -i --rm -p 9004:9004 quarkus/rimfrost-regel-rtf-manuell-komplettering-bff
#
###
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.10
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root --chmod=0755 target/*-runner /work/application

EXPOSE 9004
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
